version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/weatherapp
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - mongo-init

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  mongo-init:
    image: mongo:4.4
    depends_on:
      - mongo
    entrypoint:
      [
        "/bin/sh",
        "-c",
        'until mongo --host mongo --eval ''print("waited for connection")''; do sleep 2; done && mongo --host mongo --eval ''rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongo:27017" }]});''',
      ]
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  mongodb_data:
